### ISSUE TITLE
A small delay before beginning rotating

### ISSUE THREAD

**Issue by toverux** [nolimits4web/mariko#2]
Hi, thanks for your amazing library, I integrated it in a few minutes in a landing page and it's effectively stunning at low cost.

I noticed that there is a short delay when the mouse hovers a mariko block, where no rotation happens. First the block scales, then rotation happens according to mouse movements.
It's not long, but it can definitely be felt.

![Peek 01-07-2021 11-48](https://user-images.githubusercontent.com/1343250/124105325-666d7900-da63-11eb-8526-fcc3871e6c9f.gif)

I guess this delay is not tight to the scaling though, since disabling the offset/duration properties don't have an impact on this.
I thought it might be on purpose, to avoid too much movement eg. if the user is hovering multiple mariko'ed blocks when moving its cursor across the page.

However, in my use cas, it feels less natural. Can it be disabled, if that's technically possible?

**Comment by nolimits4web** [comment]
Hi! This is by design. And there is a `rotateLock` parameter that does it https://marikojs.com/docs#parameters

> When enabled, it won't rotate the container until pointer move out from originally entered quarter

**Comment by toverux** [comment]
Oh, I didn't understand the description at first, should have tried it. Sorry and thanks for the hint!
